name: hj_lib
# description: >-
#   Have you been turned into a newt?  Would you like to be?
#   This package can help. It has all of the
#   newt-transmogrification functionality you have been looking
#   for.
version: 0.0.1
# homepage: https://example-pet-store.com/newtify
# documentation: https://example-pet-store.com/newtify/docs

environment:
  sdk: '>=2.17.1 <3.0.0'
  
# dependencies:
  
dev_dependencies:
  test: '>=1.15.0 <2.0.0'
  objectbox_generator: any
  build_runner: ^2.1.11

dependencies:
  cryptography: ^2.0.5
  cryptography_flutter: ^2.0.2
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  objectbox: ^1.5.0
  objectbox_flutter_libs: any
